# This is a basic workflow to help you get started with Actions

name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare
        if: success()
        id: prepare
        run: |
          re="^FROM caddy:([^-]+)"
          str=$(cat Dockerfile)
          tag=$(if [[ $str =~ $re ]]; then echo ${BASH_REMATCH[1]}; else exit 1; fi)
          echo "tag=$tag" >> $GITHUB_ENV
          echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build container and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ env.repo_name }}:${{ env.tag }}
            ghcr.io/${{ env.repo_name }}:latest

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag }}
